travis:
  secure:
    BINSTAR_TOKEN: 15O47Bd4JHJR/QY6GSFlKnpod4zBOrsKSc4hRqOwUoDhrZu9rR3Fns0lrlodxvYAc9fxI6eHrKU/zqEXX6i5mTB9APNiZQZUXBKlAvXuOKE28njzuque2ZuLL5q9Q3DQsgQnQ3QTXlaTIxtwhWoG4qEOA6LcijPWv4QdzyuCXmmVuKBolcbiqReh1ueEJGBHHSOc0PpX1tFVfjUdR71DikrGlFx/w+KXAeTS09enuM9KFieK8tRV+EaxvVfrZbNvWeNg5ut1VBYyHfWOYRqamybC3iZ3SDAWYxJHfSExJrHEQPIsHG7ONOGgkp3PJcm+96wlgbMDychBPGjZ7AzYhyd5XXhep6YWwBp1sqtgg1K8mJI9dsY1JykD8CooBMF3HuNmxDu/86uWR5iCVP27T+3nBszZYGpJmJnbXBS1YL2hvnnTCJ8V0puKvCJlLDshYCUMwsOWUDSPVCVV5+f9mxFattAIpkxCeulrq9hGnVm9dI9vKEbICeCH7plEJRkfrylaqxA761eVwtJF2x5oaZUr76BJg+HM3j7JZbP4etE3mmg1y5L7RuvyfYK4gWWORDl9QtBzMJQjpNkpxAOCjR5tmn/zmD65cnxTvH4YYjYL1oREZqsRhnmzMhFUquYyzvu3SZuyWsjB5cAcWHCff1RtyLVVHgPR3QxoZJeoWRc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
